apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-k8s
  labels:
    app: spring-boot-k8s
spec:
  replicas: 1  # Number of replicas
  selector:
    matchLabels:
      app: spring-boot-k8s
  template:
    metadata:
      labels:
        app: spring-boot-k8s
    spec:
      containers:
        - name: spring-boot-k8s
          image: priyanshubirla/myapp:latest  # Corrected image name
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://tramway.proxy.rlwy.net:55144/railway"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "dPdXjZRAutdqNBLzvAmyZPMLaarNaFLm"
            - name: SPRING_REDIS_HOST
              value: "redis-service"  # Internal Kubernetes Redis service
            - name: SPRING_REDIS_PORT
              value: "6379"
            - name: SPRING_REDIS_PASSWORD
              value: "1lqRL8GTps0PMO4a2Ek4MjU5ZHggQZfg"
          resources:
            limits:
              memory: "2Gi"   # Increased memory limit for better performance
              cpu: "2"        # Allocating 2 full CPU cores for high performance
            requests:
              memory: "1Gi"   # Minimum memory request for stability
              cpu: "1"        # Reserving 1 full CPU core for smooth execution

---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-nodeport
spec:
  type: NodePort
  selector:
    app: spring-boot-k8s
  ports:
    - protocol: TCP
      port: 80          # Internal cluster port
      targetPort: 8081  # Port on the container
      nodePort: 30007   # External port (between 30000-32767)
